import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { DataSource } from 'typeorm';
import {
  initializeTransactionalContext,
  StorageDriver,
} from 'typeorm-transactional';
import * as request from 'supertest';

import { AppModule } from '../src/app.module';

// This boots the real app, with a real Postgres connection (see
// docker-compose.yml) and real transactions/locks - it exercises the exact
// path a unit test can't: the actual SQL generated by the repositories.
// initializeTransactionalContext() is normally called once in main.ts
// before the app boots; the test module bypasses main.ts, so it has to be
// called here too, or every @Transactional() method would throw.
initializeTransactionalContext({ storageDriver: StorageDriver.AUTO });

describe('Order cart flow (e2e)', () => {
  let app: INestApplication;
  let dataSource: DataSource;
  const runId = Date.now();

  async function registerAndLogin(email: string) {
    await request(app.getHttpServer()).post('/auth/register').send({
      firstName: 'Test',
      lastName: 'User',
      email,
      password: 'Password123!',
    });

    const response = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ email, password: 'Password123!' });

    return response.body.access_token as string;
  }

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    dataSource = app.get(DataSource);
  }, 30000);

  afterAll(async () => {
    await app.close();
  });

  it('lets a buyer add a seller product to the cart, merge quantities, and recalculates totals', async () => {
    const sellerToken = await registerAndLogin(`seller-${runId}@test.com`);
    const buyerToken = await registerAndLogin(`buyer-${runId}@test.com`);

    const categoriesResponse = await request(app.getHttpServer())
      .get('/category')
      .set('Authorization', `Bearer ${sellerToken}`);
    const categoryId = categoriesResponse.body[0].id;

    const [{ id: subcategoryId }] = await dataSource.query(
      'SELECT id FROM subcategories LIMIT 1',
    );

    const storeResponse = await request(app.getHttpServer())
      .post('/store')
      .set('Authorization', `Bearer ${sellerToken}`)
      .send({
        name: `Store ${runId}`,
        description: 'An e2e test store',
        categories: [categoryId],
      });

    const productResponse = await request(app.getHttpServer())
      .post('/product')
      .set('Authorization', `Bearer ${sellerToken}`)
      .send({
        name: `Product ${runId}`,
        description: 'An e2e test product',
        store: storeResponse.body.id,
        subcategory: subcategoryId,
        price: 100,
        currency: 'MXN',
        quantity: 10,
      });
    const productId = productResponse.body.id;

    const firstAdd = await request(app.getHttpServer())
      .post('/order/item')
      .set('Authorization', `Bearer ${buyerToken}`)
      .send({ productId, productQuantity: 2 })
      .expect(201);

    expect(firstAdd.body.status).toBe('CART');
    expect(firstAdd.body.subtotalAmount).toBe('200.00');
    expect(firstAdd.body.orderItems).toHaveLength(1);
    expect(firstAdd.body.orderItems[0].quantity).toBe(2);

    const secondAdd = await request(app.getHttpServer())
      .post('/order/item')
      .set('Authorization', `Bearer ${buyerToken}`)
      .send({ productId, productQuantity: 3 })
      .expect(201);

    expect(secondAdd.body.id).toBe(firstAdd.body.id);
    expect(secondAdd.body.orderItems).toHaveLength(1);
    expect(secondAdd.body.orderItems[0].quantity).toBe(5);
    expect(secondAdd.body.subtotalAmount).toBe('500.00');
    expect(secondAdd.body.totalAmount).toBe('500.00');

    await request(app.getHttpServer())
      .post('/order/item')
      .set('Authorization', `Bearer ${buyerToken}`)
      .send({ productId, productQuantity: 100 })
      .expect(400);

    await request(app.getHttpServer())
      .post('/order/item')
      .set('Authorization', `Bearer ${sellerToken}`)
      .send({ productId, productQuantity: 1 })
      .expect(400);
  });

  it('rejects adding a product without authentication', async () => {
    await request(app.getHttpServer())
      .post('/order/item')
      .send({ productId: 1, productQuantity: 1 })
      .expect(401);
  });
});
